services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
    - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
    - zookeeper
    ports:
    - 29092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
    - zookeeper
    - kafka
    profiles:
    - ui
    ports:
    - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  metrics-ingest:
    image: metrics-ingest:latest
    depends_on:
    - zookeeper
    - kafka
    ports:
    - 8000:8000
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  
  metrics-ensemble:
    image: metrics-ensemble:latest
    depends_on:
    - zookeeper
    - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

